### ISSUE TITLE
Search shell functions

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/alias-search#11]
Right now we only search aliases.

For this, it depends how people annotate the functions as they can annotate inline or like I do below:

```bash
# Update readme commit
gz(){
  # TODO: if 'readme.md' files exists, update it instead
  git add README.md
  git commit -m "readme: update"
  git push
}
```

Where it's comment on line above function definition.

I think we should use that as commenting inline is not good practice anyway.

**Comment by johnletey** [comment]
Here's a [regex](https://regex101.com/r/HE8hys/8) that works for the above example (note that it also works when you have a parameter to the function and a space after the right parentheses and before the curly bracket)

**Comment by nikitavoloboev** [comment]
Awesome. Let's use that :)
