### ISSUE TITLE
Think of a new name

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/alias-search#13]
The tool no longer only searches aliases but also functions and soon other commands too. 

I think it should have a new name. 🙂

**Comment by johnletey** [comment]
@nikitavoloboev `term-search`?

**Comment by nikitavoloboev** [comment]
Too vague. It has to be tied to the shell I think

**Comment by johnletey** [comment]
@nikitavoloboev I see ... what about `shell-search` or even `enviro-search` (because it's searching your shell environment)?

**Comment by nikitavoloboev** [comment]
I like `shell-search`. Will rename it to that. :)

**Comment by johnletey** [comment]
Great!
