### ISSUE TITLE
Scan through user aliases

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/alias-search#4]
Read comments attached to aliases. So I should scan files where aliases are defined.

i.e. 

```Bash
alias g='git add .' # Add all files to commit
```

Will capture both the alias trigger, the command it triggers and the comment attached to it inline.

**Comment by nikitavoloboev** [comment]
Can get aliases by running `alias`

**Comment by nikitavoloboev** [comment]
Read comments attached to aliases. So I should scan files where aliases are defined.

i.e. 

```Bash
alias g='git add .' # Add all files to commit
```

**Comment by johnletey** [comment]
This [regex](https://regex101.com/r/HE8hys/6) should be able to parse aliases like the one above

**Comment by johnletey** [comment]
@nikitavoloboev I have a rough draft for this ... I'll open a PR once #7 is merged

**Comment by nikitavoloboev** [comment]
Merged

**Comment by johnletey** [comment]
@nikitavoloboev #8
